logging_level: 20
matplotlib:
  font:
    family: serif
    sans_serif:
      - Helvetica
    serif:
      - "Computer Modern Roman"

data:
  download: true
  ignore_download_cache: false
  start_date: "2007-01-01"
  end_date: "2024-12-31"

preprocess:
  compute_earning_surprises: false

tasks:
  build_panel: false
  save_panel: false
  load_panel: true

# figures:
#   n_stocks_per_year: true
#   n_earnings_per_year: true

# tables:
#   ea_regression: true